FROM debian:stretch-slim

MAINTAINER Václav Pelíšek <peldax@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# Error: invoke-rc.d: policy-rc.d denied execution of restart.
RUN sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d

# Populate repositories
RUN apt-get update

# Install core utilities
RUN apt-get install -y --no-install-recommends \
    dialog \
    apt-utils \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    openssl

# Install toolbox
RUN apt-get install -y --no-install-recommends \
    mc \
    git \
    nano \
    htop \
    nmap \
    wget \
    curl

# Add PHP repository
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

# Add Testing repository
RUN sh -c 'echo "deb http://ftp.cz.debian.org/debian/ testing main" > /etc/apt/sources.list.d/testing.list'

# Add NodeJS repository
RUN curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

RUN apt-get update

# Install Apache
RUN apt-get install -y --no-install-recommends \
    apache2
RUN a2enmod ssl && \
    a2enmod deflate && \
    a2enmod rewrite && \
    a2enmod include && \
    a2enmod autoindex

# Install PHP
RUN apt-get install -y --no-install-recommends \
    php7.1 \
    php7.1-cli \
    php7.1-curl \
    php7.1-intl \
    php7.1-gd \
    php7.1-mbstring \
    php7.1-mcrypt \
    php7.1-pdo \
    php7.1-mysql \
    php7.1-json \
    php7.1-zip \
    php7.1-xml \
    php7.1-imagick \
    php7.1-redis \
    php7.1-igbinary \
    libapache2-mod-php7.1

RUN apt-get install -y --no-install-recommends \
    composer
    nodejs

# Copy configuration
COPY ./apache2/000-default.conf /etc/apache2/sites-enabled/

# SSL certificate
#RUN if [ ! -e node_modules ]; then ln -s www/node_modules node_modules fi
#RUN openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365

# Copy executable files
COPY ./bin/startup.sh /usr/local/bin/
COPY ./bin/scss.sh /usr/local/bin/
COPY ./bin/js.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/scss.sh
RUN chmod +x /usr/local/bin/js.sh

CMD /usr/local/bin/startup.sh

# Enable ports
EXPOSE 80
EXPOSE 443

# Cleanup
RUN rm -rf /var/lib/apt/lists/* && apt-get clean
